// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-students.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_students_default = defineTool({
  name: "list_students",
  title: "List students",
  description: "List students the caller can access. Optional name substring filter (case-insensitive). Returns up to 100 rows.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional substring to match against the student name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client(ctx).from("students").select("id, name, start_date, school_id").order("name").limit(100);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { students: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-attendance.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.2";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_attendance_default = defineTool2({
  name: "get_attendance",
  title: "Get attendance for a date",
  description: "Return attendance records for a specific date (YYYY-MM-DD). Optionally filter by student_id. Defaults to today.",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("ISO date (YYYY-MM-DD). Defaults to today."),
    student_id: z2.string().uuid().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, student_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const target = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let q = client2(ctx).from("attendance").select("id, date, status, student_id, time_slot_id, is_justified, absence_note, students(name), time_slots(day_of_week, start_time, end_time)").eq("date", target).order("date", { ascending: false }).limit(500);
    if (student_id) q = q.eq("student_id", student_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { date: target, records: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-birthdays.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.2";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_birthdays_default = defineTool3({
  name: "list_birthdays",
  title: "List birthdays for a month",
  description: "List students whose birthday falls in the given month (1-12). Defaults to the current month.",
  inputSchema: {
    month: z3.number().int().min(1).max(12).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const m = month ?? (/* @__PURE__ */ new Date()).getMonth() + 1;
    const { data, error } = await client3(ctx).from("students").select("id, name, birth_date, school_id").not("birth_date", "is", null).limit(1e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const filtered = (data ?? []).filter((s) => {
      const bd = s.birth_date ? new Date(s.birth_date) : null;
      return bd && bd.getUTCMonth() + 1 === m;
    }).sort((a, b) => new Date(a.birth_date).getUTCDate() - new Date(b.birth_date).getUTCDate());
    return {
      content: [{ type: "text", text: JSON.stringify(filtered) }],
      structuredContent: { month: m, students: filtered }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vbffeprxfveocgcrdten";
var mcp_default = defineMcp({
  name: "cnt-informatica-mcp",
  title: "CNT Inform\xE1tica",
  version: "0.1.0",
  instructions: "Read-only tools for the CNT Inform\xE1tica school management system. Use list_students to look up students, get_attendance to inspect attendance for a given day, and list_birthdays for a monthly birthday list. All access respects the caller's school and role permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_students_default, get_attendance_default, list_birthdays_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
